### ISSUE TITLE
Ergonomie: descendre le layout des #lighting/clusters 

### ISSUE THREAD

**Issue by PrrLjn** [ptocquin/velire#13]
Une fois que les #lighting par clusters sont définis, on n'y touche plus trop, par contre on utilise assez souvent les boutons de clusters, qui sont en dessous pour l'instant. Du coup , faut beaucoup faire glisser l'écran de bas en haut. Ce serait plus ergonomique d'inverser les positions des deux layouts.

**Comment by ptocquin** [comment]
Oui, à terme je peux les séparer sur 2 onglets/pages avec un bouton pour basculer d'un affichage à un autre
