### ISSUE TITLE
Valeurs par défaut quand on édite un run

### ISSUE THREAD

**Issue by PrrLjn** [ptocquin/velire#14]
Par example, on veut seulement changer l'heure, on ne fait pas attention au programme qui par défaut est celui du haut de la liste. Du coup c'est le mauvais programme qui est sauvé.
A l'inverse,  on change seulement le programme mais l'heure de départ est mise à l'heure courante.
Ce serait mieux que les défauts soient les valeurs précedemment encodées

**Comment by ptocquin** [comment]
Corrigé
