### ISSUE TITLE
Amélioration section clusters

### ISSUE THREAD

**Issue by PrrLjn** [ptocquin/velire#8]
(si possible), ce serait plus pratique de lister les luminaires par 3 rangées de 5 plutôt que 5 colonnes de 3. 
cad:
1  2  3  4  5
6  7  8  9  10
11 12 13 14 15
Plutôt que:
1  4  7  10  13
2  5  8  11  14
3  6  9  12  15

**Comment by ptocquin** [comment]
Pas encore parfait mais la logique de mettre en ligne est appliquée
